--Ion GUI, a World of Warcraft® user interface addon.
--Copyright© 2006-2012 Connor H. Chenoweth, aka Maul - All rights reserved.

local L = LibStub("AceLocale-3.0"):NewLocale("IonGUI", "enUS", true)

L.APPLY = "Apply"
L.CANCEL = "Cancel"
L.DONE = "Done"
L.CREATE_BAR = "Create New Bar"
L.DELETE_BAR = "Delete Current Bar"
L.SELECT_BAR_TYPE = "- Select Bar Type -"
L.CONFIRM = "- Confirm -"
L.CONFIRM_YES = "Yes"
L.CONFIRM_NO = "No"
L.GENERAL = "General Options"
L.BAR_STATES = "Bar States"
L.OBJECTS = "Object Editor"
L.MACRO = "Macro Data"
L.ACTION = "Action Data"
L.OPTIONS = "Options"

L.MACRO_NAME = "-macro name-"
L.MACRO_EDITNOTE = "Click here to edit macro note"
L.MACRO_USENOTE = "Use macro note as button tooltip"

L.COUNT = "Count"
L.SEARCH = "Search"
L.CUSTOM_ICON = "Custom Icon"
L.PATH = "path"

L.AUTOHIDE = "Auto Hide"
L.SHOWGRID = "Show Grid"
L.SNAPTO = "Snap To"
L.HIDDEN = "Hidden"
L.UPCLICKS = "Up Clicks"
L.DOWNCLICKS = "Down Clicks"
L.DUALSPEC = "Dual Spec"
L.SPELLGLOW = "Spell Alerts"
L.SPELLGLOW_DEFAULT = " - Default Alert"
L.SPELLGLOW_ALT = " - Subdued Alert"
L.LOCKBAR = "Lock Actions"
L.LOCKBAR_SHIFT = " - Unlock on SHIFT"
L.LOCKBAR_CTRL = " - Unlock on CTRL"
L.LOCKBAR_ALT = " - Unlock on ALT"
L.TOOLTIPS = "Enable Tooltips"
L.TOOLTIPS_ENH = " - Enhanced"
L.TOOLTIPS_COMBAT = " - Hide in Combat"

L.PRESET_STATES = "Preset Action States"
L.CUSTOM_STATES = "Custom Action States"

L.PAGED = "Paged"
L.STANCE = "Stance"
L.PET = "Pet"
L.ALT = "Alt"
L.CTRL = "Ctrl"
L.SHIFT = "Shift"
L.STEALTH = "Stealth"
L.REACTION = "Reaction"
L.COMBAT = "Combat"
L.GROUP = "Group"
L.FISHING = "Fishing"
L.VEHICLE = "Vehicle"
L.POSSESS = "Possess"
L.OVERRIDE = "Override"
L.EXTRABAR = "Extra Bar"
L.CUSTOM = "Custom"
L.PROWL = "Prowl"

L.REMAP = "Primary State to Remap"
L.REMAPTO = "Remap State To"

L.SCALE = "Scale"
L.ALPHA = "Alpha"
L.ALPHAUP = "Alpha Up"
L.ALPHAUP_SPEED = "A/U Speed"
L.STRATA = "Strata"
L.SHAPE = "Shape"
L.HPAD = "Horiz Pad"
L.VPAD = "Vert Pad"
L.HVPAD = "H + V Pad"
L.COLUMNS = "Columns"
L.ARCSTART = "Arc Start"
L.ARCLENGTH = "Arc Length"

L.BINDTEXT = "Bind Text"
L.MACROTEXT = "Macro Text"
L.COUNTTEXT = "Count Text"
L.RANGEIND = "Range Ind"
L.CDTEXT = "Cooldown Text"
L.CDALPHA = "Cooldown Alpha"
L.AURATEXT = "Aura Watch Text"
L.AURAIND = "Aura Watch Ind"

L.POINT = "Point"
L.XPOS = "X Pos"
L.YPOS = "Y Pos"